name: Deploy Lambda Function

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:
jobs:
  deploy:
    name: deploy to lambda
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci --production

      - name: Create deployment package
        run: |
          rm -f function.zip  # Ensure no leftover zip exists
          mkdir -p lambda-package
          cp -r node_modules lambda-package/
          rsync -av --progress . lambda-package/ --exclude lambda-package --exclude .git --exclude package-lock.json
          cd lambda-package
          zip -r ../function.zip .
      
      - name: Verify ZIP contents
        run: unzip -l function.zip


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://function.zip
